# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ObjectListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ObjectListWidget.setGeometry(QtCore.QRect(10, 50, 256, 192))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(12)
        self.ObjectListWidget.setFont(font)
        self.ObjectListWidget.setObjectName("ObjectListWidget")
        self.TargetListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.TargetListWidget.setGeometry(QtCore.QRect(280, 50, 256, 192))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(12)
        self.TargetListWidget.setFont(font)
        self.TargetListWidget.setObjectName("TargetListWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(230, 270, 93, 28))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(12)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "可選擇的夾取物件列表"))
        self.label_2.setText(_translate("MainWindow", "可選擇的放置位置列表"))
        self.confirmButton.setText(_translate("MainWindow", "確認送出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
