# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(20, 70, 401, 291))
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.RealTimeVideo = QtWidgets.QLabel(self.centralwidget)
        self.RealTimeVideo.setGeometry(QtCore.QRect(40, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(24)
        self.RealTimeVideo.setFont(font)
        self.RealTimeVideo.setObjectName("RealTimeVideo")
        self.CapturedImage = QtWidgets.QLabel(self.centralwidget)
        self.CapturedImage.setGeometry(QtCore.QRect(530, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(24)
        self.CapturedImage.setFont(font)
        self.CapturedImage.setObjectName("CapturedImage")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(510, 80, 401, 291))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(150, 400, 151, 51))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(20)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RealTimeVideo.setText(_translate("MainWindow", "REAL TIME VIDEO"))
        self.CapturedImage.setText(_translate("MainWindow", "CAPTURED IMAGE"))
        self.startButton.setText(_translate("MainWindow", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
